### ISSUE TITLE
propose: ERP, CRM and customer Management

### ISSUE THREAD

**Issue by joubertredrat** [n1trux/awesome-sysadmin#76]
A lot of sysadmins works as freelance, then I think that is good idea to have this topic to have solutions for this, to sysadmin use in your projects or to implement in your clients.

**Comment by n1trux** [comment]
do it, let's see how this goes.

I think we should consider moving this to a dedicated website like alternativeto.net is, only for recommendations instead of alternatives.

There must be something out there which allows software collections like this to be sorted in a nice way. We currently have just a list, and to be honest, a list sucks. I wouldn't know what to use right now. We don't have any tutorials or testimonials connecting the various pieces...

**Comment by joubertredrat** [comment]
@n1trux I understand this, we can create new branch to improve site using gh-pages, then we can display solutions by tag and visitor can filter by tags or sections.
